### PR TITLE
Some small improvements…

### PR DESCRIPTION
**Pull request by thierrymichel**
Thanks for this extension!
I've added 'disable-next-line' snippet with a 'rule' placeholder.

Hope you will merge it! :)

### CODE REVIEW

**Comment by thierrymichel** [comment]
Up! :)

**Comment by drKnoxy** [comment]
awesome 🏆

**Comment by drKnoxy** [comment]
writing up a new release, did you want your twitter handle in the credits? found it via github->site->twitter but didn't want to distribute it to the tens of users without your consent :D

**Comment by thierrymichel** [comment]
It’s up to you 😉.
Thanks for the merge 👍

**Pull request merged**
